trigger:
  branches:
    include:
      - main
  
  tags:
    include:
      - v*

pool:
  vmImage: ubuntu-latest

stages:
  - stage: analyze
    displayName: Analyze
    jobs:
    - job: format
      displayName: rustfmt
      container:
        image: rust:1.76.0-bookworm
      
      steps:
        - script: rustup component add rustfmt
          displayName: Install rustfmt
        - script: cargo fmt --check
          displayName: Run formatter

    - job: clippy
      displayName: clippy
      container:
        image: rust:1.76.0-bookworm
      
      steps:
        - script: rustup component add clippy
          displayName: Install clippy
        - script: cargo clippy --no-deps -- --deny="warnings"
          displayName: Run clippy
          
  - stage: build
    displayName: Build
    jobs:
    - job: strem
      displayName: build-strem
      container:
        image: rust:1.76.0-bookworm
      
      steps:
        - script: cargo build
          displayName: Compile package
    
    - job: stremexport
      displayName: build-strem-export
      container:
        image: rust:1.76.0-bookworm
      
      steps:
        - script: cargo build --features="export"
          displayName: Compile package

  - stage: unittest
    displayName: Unit Tests
    jobs:
    - job: libunittest
      displayName: unittest-strem-lib
      container:
        image: rust:1.76.0-bookworm
      
      steps:
        - script: cargo test --all-features --lib
          displayName: Run tests

    - job: binstremunittest
      displayName: unittest-strem-bin
      container:
        image: rust:1.76.0-bookworm
      
      steps:
        - script: cargo test --all-features --bin="strem"
          displayName: Run tests

  - stage: docs
    displayName: Documentation
    jobs:
    - job: docsstremlib
      displayName: docs-strem-lib
      container:
        image: rust:1.76.0-bookworm
      
      steps:
        - script: cargo doc --no-deps --document-private-items --all-features --lib
          displayName: Compile documentation
        - publish: $(Build.SourcesDirectory)/target/doc/strem/
          displayName: Publish artifact
          artifact: docs

  - stage: deploy
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/v'))
    displayName: Deploy
    jobs:
      - job: github
        displayName: GitHub
        container:
          image: bitnami/git:2.44.0

        steps:
          - script: echo "deploying..."

  - stage: publish
    condition: and(succeeded(), contains(variables['Build.SourceBranch'], 'refs/tags/v'))
    displayName: Publish
    jobs:
      - job: crates
        displayName: crates.io
        container:
          image: rust:1.76.0-bookworm
      
        steps:
          - script: echo "publishing..."