docs_dir: src/

site_name: Spatio-Temporal Regular Expression Matching
site_url: https://cps-atlas.github.io/strem

repo_url: https://github.com/cps-atlas/strem
repo_name: cps-atlas/strem

nav:
  - Home: index.md
  - Getting Started:
      - Installation: started/installation.md
      - Examples: started/examples.md
  - Reference:
      - Spatial Regular Expressions: reference/spre.md
      - Data Schema: reference/schema.md
  - About:
      - Contributors: about/contributors.md
      - Papers: about/papers.md
      - Contact: about/contact.md

theme:
  name: material
  palette:
    - scheme: default
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-7
        name: Toggle Dark Mode

    - scheme: slate
      primary: blue grey
      accent: blue grey
      toggle:
        icon: material/brightness-4
        name: Toggle Light Mode
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - navigation.expand

copyright: Copyright &copy; 2023 - 2024 Spatial Regular Expression Matching Organization

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - toc:
      permalink: "#"
